// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: coordinator/proto/fleet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BenchmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	BotCount      int32                  `protobuf:"varint,2,opt,name=bot_count,json=botCount,proto3" json:"bot_count,omitempty"`
	OrdersPerBot  int32                  `protobuf:"varint,3,opt,name=orders_per_bot,json=ordersPerBot,proto3" json:"orders_per_bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchmarkRequest) Reset() {
	*x = BenchmarkRequest{}
	mi := &file_coordinator_proto_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRequest) ProtoMessage() {}

func (x *BenchmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRequest.ProtoReflect.Descriptor instead.
func (*BenchmarkRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *BenchmarkRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *BenchmarkRequest) GetBotCount() int32 {
	if x != nil {
		return x.BotCount
	}
	return 0
}

func (x *BenchmarkRequest) GetOrdersPerBot() int32 {
	if x != nil {
		return x.OrdersPerBot
	}
	return 0
}

type BenchmarkResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders      int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	SuccessfulOrders int32                  `protobuf:"varint,2,opt,name=successful_orders,json=successfulOrders,proto3" json:"successful_orders,omitempty"`
	FailedOrders     int32                  `protobuf:"varint,3,opt,name=failed_orders,json=failedOrders,proto3" json:"failed_orders,omitempty"`
	FailureRate      float64                `protobuf:"fixed64,4,opt,name=failure_rate,json=failureRate,proto3" json:"failure_rate,omitempty"`
	FleetTimeMs      float64                `protobuf:"fixed64,5,opt,name=fleet_time_ms,json=fleetTimeMs,proto3" json:"fleet_time_ms,omitempty"`
	Tps              float64                `protobuf:"fixed64,6,opt,name=tps,proto3" json:"tps,omitempty"`
	AverageLatencyMs float64                `protobuf:"fixed64,7,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	MinLatencyMs     float64                `protobuf:"fixed64,8,opt,name=min_latency_ms,json=minLatencyMs,proto3" json:"min_latency_ms,omitempty"`
	MaxLatencyMs     float64                `protobuf:"fixed64,9,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,10,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P90LatencyMs     float64                `protobuf:"fixed64,11,opt,name=p90_latency_ms,json=p90LatencyMs,proto3" json:"p90_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,12,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BenchmarkResponse) Reset() {
	*x = BenchmarkResponse{}
	mi := &file_coordinator_proto_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResponse) ProtoMessage() {}

func (x *BenchmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResponse.ProtoReflect.Descriptor instead.
func (*BenchmarkResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *BenchmarkResponse) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *BenchmarkResponse) GetSuccessfulOrders() int32 {
	if x != nil {
		return x.SuccessfulOrders
	}
	return 0
}

func (x *BenchmarkResponse) GetFailedOrders() int32 {
	if x != nil {
		return x.FailedOrders
	}
	return 0
}

func (x *BenchmarkResponse) GetFailureRate() float64 {
	if x != nil {
		return x.FailureRate
	}
	return 0
}

func (x *BenchmarkResponse) GetFleetTimeMs() float64 {
	if x != nil {
		return x.FleetTimeMs
	}
	return 0
}

func (x *BenchmarkResponse) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *BenchmarkResponse) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *BenchmarkResponse) GetMinLatencyMs() float64 {
	if x != nil {
		return x.MinLatencyMs
	}
	return 0
}

func (x *BenchmarkResponse) GetMaxLatencyMs() float64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *BenchmarkResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *BenchmarkResponse) GetP90LatencyMs() float64 {
	if x != nil {
		return x.P90LatencyMs
	}
	return 0
}

func (x *BenchmarkResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

var File_coordinator_proto_fleet_proto protoreflect.FileDescriptor

const file_coordinator_proto_fleet_proto_rawDesc = "" +
	"\n" +
	"\x1dcoordinator/proto/fleet.proto\x12\vcoordinator\"l\n" +
	"\x10BenchmarkRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tbot_count\x18\x02 \x01(\x05R\bbotCount\x12$\n" +
	"\x0eorders_per_bot\x18\x03 \x01(\x05R\fordersPerBot\"\xcd\x03\n" +
	"\x11BenchmarkResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12+\n" +
	"\x11successful_orders\x18\x02 \x01(\x05R\x10successfulOrders\x12#\n" +
	"\rfailed_orders\x18\x03 \x01(\x05R\ffailedOrders\x12!\n" +
	"\ffailure_rate\x18\x04 \x01(\x01R\vfailureRate\x12\"\n" +
	"\rfleet_time_ms\x18\x05 \x01(\x01R\vfleetTimeMs\x12\x10\n" +
	"\x03tps\x18\x06 \x01(\x01R\x03tps\x12,\n" +
	"\x12average_latency_ms\x18\a \x01(\x01R\x10averageLatencyMs\x12$\n" +
	"\x0emin_latency_ms\x18\b \x01(\x01R\fminLatencyMs\x12$\n" +
	"\x0emax_latency_ms\x18\t \x01(\x01R\fmaxLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\n" +
	" \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep90_latency_ms\x18\v \x01(\x01R\fp90LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\f \x01(\x01R\fp99LatencyMs2a\n" +
	"\x10FleetCoordinator\x12M\n" +
	"\fRunBenchmark\x12\x1d.coordinator.BenchmarkRequest\x1a\x1e.coordinator.BenchmarkResponseB3Z1github.com/ShriChinmay/Crucible/coordinator/protob\x06proto3"

var (
	file_coordinator_proto_fleet_proto_rawDescOnce sync.Once
	file_coordinator_proto_fleet_proto_rawDescData []byte
)

func file_coordinator_proto_fleet_proto_rawDescGZIP() []byte {
	file_coordinator_proto_fleet_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_fleet_proto_rawDesc), len(file_coordinator_proto_fleet_proto_rawDesc)))
	})
	return file_coordinator_proto_fleet_proto_rawDescData
}

var file_coordinator_proto_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coordinator_proto_fleet_proto_goTypes = []any{
	(*BenchmarkRequest)(nil),  // 0: coordinator.BenchmarkRequest
	(*BenchmarkResponse)(nil), // 1: coordinator.BenchmarkResponse
}
var file_coordinator_proto_fleet_proto_depIdxs = []int32{
	0, // 0: coordinator.FleetCoordinator.RunBenchmark:input_type -> coordinator.BenchmarkRequest
	1, // 1: coordinator.FleetCoordinator.RunBenchmark:output_type -> coordinator.BenchmarkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coordinator_proto_fleet_proto_init() }
func file_coordinator_proto_fleet_proto_init() {
	if File_coordinator_proto_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_fleet_proto_rawDesc), len(file_coordinator_proto_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_fleet_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_fleet_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_fleet_proto_msgTypes,
	}.Build()
	File_coordinator_proto_fleet_proto = out.File
	file_coordinator_proto_fleet_proto_goTypes = nil
	file_coordinator_proto_fleet_proto_depIdxs = nil
}
