// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: coordinator/proto/fleet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetCoordinator_RunBenchmark_FullMethodName = "/coordinator.FleetCoordinator/RunBenchmark"
)

// FleetCoordinatorClient is the client API for FleetCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetCoordinatorClient interface {
	RunBenchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*BenchmarkResponse, error)
}

type fleetCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetCoordinatorClient(cc grpc.ClientConnInterface) FleetCoordinatorClient {
	return &fleetCoordinatorClient{cc}
}

func (c *fleetCoordinatorClient) RunBenchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*BenchmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BenchmarkResponse)
	err := c.cc.Invoke(ctx, FleetCoordinator_RunBenchmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetCoordinatorServer is the server API for FleetCoordinator service.
// All implementations must embed UnimplementedFleetCoordinatorServer
// for forward compatibility.
type FleetCoordinatorServer interface {
	RunBenchmark(context.Context, *BenchmarkRequest) (*BenchmarkResponse, error)
	mustEmbedUnimplementedFleetCoordinatorServer()
}

// UnimplementedFleetCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetCoordinatorServer struct{}

func (UnimplementedFleetCoordinatorServer) RunBenchmark(context.Context, *BenchmarkRequest) (*BenchmarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBenchmark not implemented")
}
func (UnimplementedFleetCoordinatorServer) mustEmbedUnimplementedFleetCoordinatorServer() {}
func (UnimplementedFleetCoordinatorServer) testEmbeddedByValue()                          {}

// UnsafeFleetCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetCoordinatorServer will
// result in compilation errors.
type UnsafeFleetCoordinatorServer interface {
	mustEmbedUnimplementedFleetCoordinatorServer()
}

func RegisterFleetCoordinatorServer(s grpc.ServiceRegistrar, srv FleetCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedFleetCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetCoordinator_ServiceDesc, srv)
}

func _FleetCoordinator_RunBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCoordinatorServer).RunBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetCoordinator_RunBenchmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCoordinatorServer).RunBenchmark(ctx, req.(*BenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetCoordinator_ServiceDesc is the grpc.ServiceDesc for FleetCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.FleetCoordinator",
	HandlerType: (*FleetCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBenchmark",
			Handler:    _FleetCoordinator_RunBenchmark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator/proto/fleet.proto",
}
